version: "3.9"
services:
  api:
    image: ajmezav/iam_challenge:11
    # build: # construcción de la imagen de Docker de la API
    #   context: .
    #   dockerfile: Dockerfile-api # nombre del Dockerfile de la API
    ports:
      - "8000:8000"
    links:
      - db:MYSQL # Alias para conectarse a la BD 
    depends_on:
      - db # Dependencia del servicio llamado db en este archivo
    volumes:
      - apidata:/code #persistent volume
    command: # comandos a ejecutar cuando sube el contenedor de la API
      - /bin/bash
      - -c
      - |
        python /code/Challenge_IAM/manage.py makemigrations
        python /code/Challenge_IAM/manage.py migrate
        python /code/Challenge_IAM/manage.py runserver 0.0.0.0:8000
    container_name: api-meli-iam # Alias para el contenedor de la API

  db:
    image: ajmezav/bd_iam:11
    # build:
    #   context: .
    #   dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql #persistent volume
    environment:
      - MYSQL_ROOT_PASSWORD=meli.2022
      - MYSQL_USER=MYSQL
      - MYSQL_PASSWORD=meli.2022
      - MYSQL_DATABASE=Django_api
    container_name: db-meli-iam  # Alias para el contenedor de la BD
volumes: # Volumenes persistentes creados para los contenedores
  dbdata:
  apidata: